apiVersion: v1
kind: Service # what type of resource we are creating
metadata:
  name: hello-app-service # Arbitrary name
spec:
  type: LoadBalancer # What type of service
  selector:
    app: greeting # grab pods with this key value label
  ports:
    - protocol: TCP
      port: 80 # port the load balancer
      targetPort: 3000 # port to access the pod(s) on
  